name: Build production files
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Run "npm run prod"
    env:
      APP_NAME: "Arise Global Scholarship"
      APP_SLUG: "ariseglobalscholarship"
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      APP_HOST: ${{ secrets.FLOATING_IP }}
      APP_USERNAME: ${{ secrets.USERNAME }}
      APP_PASSWORD: ${{ secrets.PASSWORD }}
      APP_PORT: ${{ secrets.PORT }}
      APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      RELEASE_TYPE: patch
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.APP_HOST }}
          username: ${{ env.APP_USERNAME }}
          key: ${{ env.APP_PRIVATE_KEY }}
          port: ${{ env.APP_PORT }}
          script: |
            whoami
            ls -al
